const API_BASE_URL = "http://localhost:5000";
const USE_MOCK_DATA = false;
const SUPPORTED_LANGUAGES = [
  { value: "en", label: "English" }, { value: "ml", label: "Malayalam" }, { value: "hi", label: "Hindi" },
  { value: "ta", label: "Tamil" }, { value: "te", label: "Telugu" }, { value: "kn", label: "Kannada" }
];
const MOCK_SERVICES = [
  { id: "mock-pmkisan", name: "PM-KISAN", category: "Agriculture", description: "Income support for eligible farmer families.", eligibility: "Small and marginal farmer families with cultivable land.", application_process: "Register through the official portal or local agriculture office." },
  { id: "mock-scholarship", name: "National Scholarship Portal", category: "Scholarships", description: "Find and apply for scholarships from one place.", eligibility: "Eligibility varies by scholarship and student category.", application_process: "Create an account, complete your profile, and submit the selected scholarship application." },
  { id: "mock-ujjwala", name: "PM Ujjwala Yojana", category: "Welfare", description: "Support for LPG connections and cleaner cooking fuel access.", eligibility: "Eligible households as defined by the scheme criteria.", application_process: "Apply through the designated official process with household documents." }
];
const TECHNOLOGIES = ["Python", "LangChain", "LlamaIndex", "FAISS", "Whisper", "Streamlit"];
const state = { services: [], category: "All", query: "", language: sessionStorage.getItem("govassist-language") || "en", sessionId: sessionStorage.getItem("govassist-session") || crypto.randomUUID() };
const $ = (selector) => document.querySelector(selector);

function saveSession() { sessionStorage.setItem("govassist-session", state.sessionId); sessionStorage.setItem("govassist-language", state.language); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[character]); }
function setConnection(online) { $("#connection-dot").className = `connection-dot ${online ? "online" : "offline"}`; $("#connection-label").textContent = online ? "Backend connected" : "Demo mode"; }
function languageOptions(selected) { return SUPPORTED_LANGUAGES.map((language) => `<option value="${language.value}" ${language.value === selected ? "selected" : ""}>${language.label}</option>`).join(""); }
function setLanguage(value) { state.language = value; document.querySelectorAll(".language-select").forEach((select) => { select.value = value; }); saveSession(); }
function renderFilters(categories) { $("#filters").innerHTML = ["All", ...categories].map((category) => `<button class="filter ${state.category === category ? "active" : ""}" data-category="${escapeHtml(category)}">${category === "All" ? "All services" : escapeHtml(category)}</button>`).join(""); document.querySelectorAll(".filter").forEach((button) => button.addEventListener("click", () => { state.category = button.dataset.category; renderFilters(categories); renderServices(); })); }
function renderServices() { const filtered = state.services.filter((service) => { const content = `${service.name} ${service.category} ${service.description || ""}`.toLowerCase(); return (state.category === "All" || service.category === state.category) && content.includes(state.query.toLowerCase()); }); $("#service-count").textContent = state.services.length; $("#service-grid").innerHTML = filtered.length ? filtered.map((service) => `<article class="service-card"><span class="card-category">${escapeHtml(service.category || "General")}</span><h3>${escapeHtml(service.name)}</h3><p>${escapeHtml(service.description || "Government service information")}</p><div class="card-footer"><span class="service-number">Service ${String(service.id).padStart(2, "0")}</span><button class="text-button details-button" data-id="${escapeHtml(service.id)}">View details -&gt;</button></div></article>`).join("") : `<p class="empty">No services match your search.</p>`; document.querySelectorAll(".details-button").forEach((button) => button.addEventListener("click", () => showServiceDetails(state.services.find((service) => String(service.id) === button.dataset.id)))); }
function showServiceDetails(service) { if (!service) return; $("#modal-content").innerHTML = `<button class="modal-close" id="close-modal" aria-label="Close service details">&times;</button><span class="card-category">${escapeHtml(service.category || "Government service")}</span><h2>${escapeHtml(service.name)}</h2><div class="detail-grid"><div><strong>Description</strong><p>${escapeHtml(service.description || "Not provided")}</p></div><div><strong>Eligibility</strong><p>${escapeHtml(service.eligibility || "See the official guidance")}</p></div><div><strong>Application procedure</strong><p>${escapeHtml(service.application_process || "Follow the official application process")}</p></div>${service.official_url ? `<div><a class="button button-dark" href="${escapeHtml(service.official_url)}" target="_blank" rel="noreferrer">Open official website -&gt;</a></div>` : ""}</div>`; $("#service-modal").classList.remove("hidden"); $("#close-modal").addEventListener("click", closeModal); }
function closeModal() { $("#service-modal").classList.add("hidden"); }
async function fetchJson(path, options = {}) { const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error?.message || "Request failed"); return payload; }
async function loadServices() { try { if (USE_MOCK_DATA) throw new Error("mock mode"); const [servicePayload, categoryPayload] = await Promise.all([fetchJson("/api/services"), fetchJson("/api/categories")]); state.services = servicePayload.services || []; renderFilters((categoryPayload.categories || []).map((category) => category.name)); renderServices(); setConnection(true); } catch (error) { state.services = MOCK_SERVICES; renderFilters([...new Set(MOCK_SERVICES.map((service) => service.category))]); renderServices(); setConnection(false); } }
function addUserMessage(message) { $("#messages").insertAdjacentHTML("beforeend", `<div class="message user">${escapeHtml(message)}</div>`); scrollMessages(); }
function addAssistantMessage(answer, sources = []) { const sourceMarkup = sources.length ? `<div class="sources"><strong>Sources</strong>${sources.map((source) => `<a class="source-link" href="${escapeHtml(source.source || "#")}" target="_blank" rel="noreferrer">${escapeHtml(source.title || source.source || "Government document")}${source.page ? ` - Page ${escapeHtml(source.page)}` : ""}</a>`).join("")}</div>` : ""; $("#messages").insertAdjacentHTML("beforeend", `<div class="message assistant">${escapeHtml(answer)}${sourceMarkup}</div>`); scrollMessages(); }
function scrollMessages() { const messages = $("#messages"); messages.scrollTop = messages.scrollHeight; }
function showLoading() { const loading = document.createElement("div"); loading.className = "message assistant loading"; loading.id = "loading-message"; loading.textContent = "GovAssist is thinking"; $("#messages").appendChild(loading); scrollMessages(); }
async function sendMessage(event) { event.preventDefault(); const input = $("#chat-input"); const message = input.value.trim(); if (!message || $("#send-button").disabled) return; addUserMessage(message); input.value = ""; input.style.height = "auto"; $("#send-button").disabled = true; $("#mic-button").disabled = true; showLoading(); try { let payload; if (USE_MOCK_DATA) { await new Promise((resolve) => setTimeout(resolve, 500)); payload = { answer: "Development response: connect the Flask backend for document-grounded answers.", sources: [] }; } else { payload = await fetchJson("/api/chat", { method: "POST", body: JSON.stringify({ message, language: state.language, session_id: state.sessionId }) }); } $("#loading-message")?.remove(); addAssistantMessage(payload.answer || "No answer was returned.", payload.sources || []); setConnection(true); } catch (error) { $("#loading-message")?.remove(); addAssistantMessage("Sorry, GovAssist could not connect to the server. Please try again."); setConnection(false); } finally { $("#send-button").disabled = false; $("#mic-button").disabled = false; input.focus(); } }
function startNewChat() { state.sessionId = crypto.randomUUID(); saveSession(); $("#messages").innerHTML = `<div class="message assistant">Hello. What government service can I help you understand today?</div>`; $("#chat-input").focus(); }
function handleVoiceInput() { const supported = "SpeechRecognition" in window || "webkitSpeechRecognition" in window; if (!supported) { addAssistantMessage("Voice input coming soon. You can type your question below."); return; } addAssistantMessage("Voice input is available in this browser, but speech-to-text is not enabled in this demo."); }
function openAssistant() { $("#assistant-modal").classList.remove("hidden"); $("#chat-input").focus(); }
function closeAssistant() { $("#assistant-modal").classList.add("hidden"); }
function renderTechnologies() { $("#tech-list").innerHTML = TECHNOLOGIES.map((technology) => `<span class="tech-item"><i data-lucide="layers"></i>${technology}</span>`).join(""); }
function initializeApp() { document.querySelectorAll(".language-select").forEach((select) => { select.innerHTML = languageOptions(state.language); select.addEventListener("change", (event) => setLanguage(event.target.value)); }); $("#chat-form").addEventListener("submit", sendMessage); $("#chat-input").addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); $("#chat-form").requestSubmit(); } }); $("#chat-input").addEventListener("input", (event) => { event.target.style.height = "auto"; event.target.style.height = `${Math.min(event.target.scrollHeight, 110)}px`; }); $("#service-search").addEventListener("input", (event) => { state.query = event.target.value; renderServices(); }); $("#new-chat").addEventListener("click", startNewChat); $("#mic-button").addEventListener("click", handleVoiceInput); $("#close-modal-backdrop").addEventListener("click", closeModal); $("#close-assistant").addEventListener("click", closeAssistant); $("#assistant-modal").addEventListener("click", (event) => { if (event.target.id === "assistant-modal") closeAssistant(); }); $("#mobile-menu").addEventListener("click", () => $("#mobile-nav").classList.toggle("hidden")); document.querySelectorAll(".open-assistant").forEach((button) => button.addEventListener("click", openAssistant)); document.addEventListener("keydown", (event) => { if (event.key === "Escape") { closeModal(); closeAssistant(); } }); renderTechnologies(); if (window.lucide) window.lucide.createIcons(); loadServices(); saveSession(); }
initializeApp();
